# workflow_engine/core/values/schema.py
"""
Pydantic models that cover the subset of the JSON Schema language generated by
Pydantic for Value subclasses.
"""

from __future__ import annotations

import inspect
import logging
from collections.abc import Mapping, Sequence
from contextvars import ContextVar
from decimal import Decimal
from enum import Enum
from functools import cached_property
from typing import Annotated, Any, ClassVar, Final, Literal, Self, TypeVar

from overrides import override
from pydantic import (
    ConfigDict,
    Field,
    SerializerFunctionWrapHandler,
    TypeAdapter,
    ValidationError,
    field_validator,
    model_serializer,
    model_validator,
)
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from ...utils.hash import json_digest
from ...utils.model import ImmutableBaseModel
from .data import Data, DataValue, build_data_type
from .datetime_value import DateValue
from .mapping import StringMapValue
from .primitives import (
    BooleanValue,
    FloatValue,
    IntegerValue,
    NullValue,
    StringValue,
)
from .sequence import SequenceValue
from .value import Value, ValueRegistry, ValueType

logger = logging.getLogger(__name__)

_T_item = TypeVar("_T_item", bound=Value)


def merge_defs(
    a: Mapping[str, ValueSchema] | None,
    b: Mapping[str, ValueSchema] | None,
) -> Mapping[str, ValueSchema] | None:
    if a is None:
        return {} if b is None else b
    if b is None:
        return {} if a is None else a
    return dict(**a, **b)


# Maps JSON Schema keywords to pydantic Field kwargs for each value category.
_NUMERIC_FIELD_MAP: dict[str, str] = {
    "minimum": "ge",
    "maximum": "le",
    "exclusiveMinimum": "gt",
    "exclusiveMaximum": "lt",
    "multipleOf": "multiple_of",
}
_STRING_FIELD_MAP: dict[str, str] = {
    "minLength": "min_length",
    "maxLength": "max_length",
    "pattern": "pattern",
}
_SEQUENCE_FIELD_MAP: dict[str, str] = {
    "minItems": "min_length",
    "maxItems": "max_length",
}
_MAP_FIELD_MAP: dict[str, str] = {
    "minProperties": "min_length",
    "maxProperties": "max_length",
}


def _enum_equal(value: Any, candidate: Any) -> bool:
    if isinstance(value, bool) or isinstance(candidate, bool):
        return value is candidate
    if isinstance(value, (int, float, Decimal)) and isinstance(
        candidate, (int, float, Decimal)
    ):
        return Decimal(str(value)) == Decimal(str(candidate))
    return value == candidate


def _additional_constraint_validators(
    field_map: dict[str, str],
    extras: Mapping[str, Any],
    *,
    in_conjunction: bool = False,
) -> list[tuple[TypeAdapter[Any] | None, Sequence[Any] | None]]:
    """Compile constraints, including conjunctions emitted for inherited bounds.

    Arbitrary JSON Schema composition is not implemented here. Reject an
    unsupported allOf clause instead of silently dropping part of a constraint.
    """
    if in_conjunction:
        unsupported = {
            key
            for key in extras
            if key not in field_map
            and key not in {"enum", "allOf", "title", "description", "$comment"}
            and not key.startswith("x-")
        }
        if unsupported:
            raise ValueError(
                f"Unsupported allOf constraint keywords: {', '.join(sorted(unsupported))}"
            )
    field_kwargs = {
        field_map[key]: value for key, value in extras.items() if key in field_map
    }
    adapter = None
    if field_kwargs:
        # Any's generic multiple_of validator uses Python's %, which is both
        # inexact for floats and invalid for Decimal % float. Decimal's native
        # Pydantic validator preserves the wire number's intended decimal value.
        adapter = (
            TypeAdapter(Annotated[Decimal, Field(**field_kwargs)])
            if field_map is _NUMERIC_FIELD_MAP
            else TypeAdapter(Annotated[Any, Field(**field_kwargs)])
        )
    enum = extras.get("enum")
    if enum is not None and not isinstance(enum, (list, tuple)):
        raise ValueError("enum must be a list of allowed values")
    validators: list[tuple[TypeAdapter[Any] | None, Sequence[Any] | None]] = (
        [(adapter, enum)] if adapter is not None or enum is not None else []
    )
    if "allOf" in extras:
        conjunction = extras["allOf"]
        if not isinstance(conjunction, (list, tuple)):
            raise ValueError("allOf must be a list of constraint objects")
        for clause in conjunction:
            if not isinstance(clause, Mapping):
                raise ValueError("allOf must contain constraint objects")
            validators.extend(
                _additional_constraint_validators(
                    field_map, clause, in_conjunction=True
                )
            )
    return validators


def _build_constrained_cls(
    base_cls: type,
    field_map: dict[str, str],
    extras: dict[str, Any],
) -> type:
    """Constrain the identified class while retaining its validators and casts.

    Validate additional constraints after the inherited root validators. Replacing
    the root annotation would discard its metadata or overwrite an intrinsic bound
    with a weaker one. Unknown keywords remain schema-only metadata.
    """
    if not extras:
        return base_cls

    validators = _additional_constraint_validators(field_map, extras)

    def validate_constraints(cls: type, value: Any) -> Any:
        comparable = value.value if isinstance(value, Enum) else value
        for adapter, enum in validators:
            if adapter is not None:
                adapter.validate_python(comparable)
            if enum is not None and not any(
                _enum_equal(comparable, item) for item in enum
            ):
                raise ValueError(f"Value must be one of {enum!r}")
        return value

    inherited_extras = base_cls.model_config.get("json_schema_extra")

    def publish_constraints(schema: dict[str, Any], model: type) -> None:
        if isinstance(inherited_extras, Mapping):
            schema.update(inherited_extras)
        elif callable(inherited_extras):
            if len(inspect.signature(inherited_extras).parameters) > 1:
                inherited_extras(schema, model)
            else:
                inherited_extras(schema)
        # The serialized schema must describe both the original and additional
        # constraints, including two different patterns or multipleOf values.
        inherited = {
            key: schema[key]
            for key, value in extras.items()
            if (key in field_map or key == "enum")
            and key in schema
            and schema[key] != value
        }
        conjunctions = list(schema.get("allOf", []))
        schema.update(extras)
        for constraint in [
            *schema.get("allOf", []),
            *([inherited] if inherited else []),
        ]:
            if constraint not in conjunctions:
                conjunctions.append(constraint)
        if conjunctions:
            schema["allOf"] = conjunctions

    unique_title = f"{base_cls.__name__}_{json_digest(extras)}"
    namespace: dict[str, Any] = {
        "model_config": base_cls.model_config
        | ConfigDict(title=unique_title, json_schema_extra=publish_constraints),
    }
    if validators:
        namespace[f"_validate_schema_constraints_{json_digest(extras)}"] = (
            field_validator("root")(classmethod(validate_constraints))
        )
    return type(base_cls.__name__, (base_cls,), namespace, register=False)


def _build_constrained_sequence_cls(
    item_type: type,
    extras: dict[str, Any],
) -> type:
    """
    Return a constrained SequenceValue subclass that remains a proper Pydantic
    generic specialisation.  Unlike calling _build_constrained_cls on an already-
    concrete SequenceValue[T], this creates an intermediate generic class and then
    binds the item type, so __pydantic_generic_metadata__ has origin=<subclass>
    (not None).  That keeps get_origin_and_args() — and therefore the casting
    system — working correctly.
    """
    field_kwargs: dict[str, Any] = {}
    schema_extras: dict[str, Any] = {}
    for key, value in extras.items():
        if key in _SEQUENCE_FIELD_MAP:
            field_kwargs[_SEQUENCE_FIELD_MAP[key]] = value
        else:
            schema_extras[key] = value

    # Include item type name so that SequenceValue[FloatValue] and
    # SequenceValue[IntegerValue] with identical extras get distinct $defs keys.
    digest = json_digest({"item_type": item_type.__name__, **extras})
    unique_title = f"SequenceValue_{digest}"

    namespace: dict[str, Any] = {}
    if field_kwargs:
        namespace["__annotations__"] = {
            "root": Annotated[Sequence[_T_item], Field(**field_kwargs)]  # type: ignore[valid-type]
        }
    config_updates: dict[str, Any] = {"title": unique_title}
    if schema_extras:
        config_updates["json_schema_extra"] = schema_extras
    namespace["model_config"] = SequenceValue.model_config | ConfigDict(
        **config_updates
    )

    cls = type("SequenceValue", (SequenceValue[_T_item],), namespace, register=False)  # type: ignore[valid-type]
    return cls[item_type]  # type: ignore[index]


def _build_constrained_map_cls(
    item_type: type,
    extras: dict[str, Any],
) -> type:
    """
    Return a constrained StringMapValue subclass using the same generic approach
    as _build_constrained_sequence_cls.
    """
    field_kwargs: dict[str, Any] = {}
    schema_extras: dict[str, Any] = {}
    for key, value in extras.items():
        if key in _MAP_FIELD_MAP:
            field_kwargs[_MAP_FIELD_MAP[key]] = value
        else:
            schema_extras[key] = value

    digest = json_digest({"item_type": item_type.__name__, **extras})
    unique_title = f"StringMapValue_{digest}"

    namespace: dict[str, Any] = {}
    if field_kwargs:
        namespace["__annotations__"] = {
            "root": Annotated[Mapping[str, _T_item], Field(**field_kwargs)]  # type: ignore[valid-type]
        }
    config_updates: dict[str, Any] = {"title": unique_title}
    if schema_extras:
        config_updates["json_schema_extra"] = schema_extras
    namespace["model_config"] = StringMapValue.model_config | ConfigDict(
        **config_updates
    )

    cls = type("StringMapValue", (StringMapValue[_T_item],), namespace, register=False)  # type: ignore[valid-type]
    return cls[item_type]  # type: ignore[index]


class BaseValueSchema(ImmutableBaseModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(
        extra="allow",
        serialize_by_alias=True,
    )

    # NOTE: recursive validation does not work unless this is a dict instead of a Mapping
    defs: dict[str, ValueSchema] = Field(
        default_factory=dict,
        serialization_alias="$defs",
        validation_alias="$defs",
    )
    title: str | None = None
    description: str | None = None
    default: Any | None = None
    const: Any | None = None
    value_type: str | None = None

    @model_validator(mode="before")
    @classmethod
    def rename_defs_alias(cls, data: Any) -> Any:
        """
        A Pydantic bug causes model_validate() to break when called on an
        instance of BaseValueSchema.
        This is because the validator receives Python attribute names from the
        object, whereas it is expecting their aliased forms.
        To fix this, we move the properties to the expected keys.
        """
        if not isinstance(data, Mapping):
            return data
        data = dict(data)
        if "$defs" not in data and "defs" in data:
            data["$defs"] = data.pop("defs")
        # Accept "x-value-type" (wire name) and map it to the Python field name.
        if "x-value-type" in data:
            value_type = data.pop("x-value-type")
            if "value_type" in data and data["value_type"] != value_type:
                raise ValueError("Conflicting value_type and x-value-type identities")
            data["value_type"] = value_type
        return data

    @model_serializer(mode="wrap")
    def serialize_without_unset(self, handler: SerializerFunctionWrapHandler):
        """
        Custom serializer that excludes unset fields by default, so we don't
        clutter the output with unused fields.
        Applies to all subclasses of BaseValueSchema.

        Newbies might do this by overriding .model_dump(), however this is a
        trap because .model_dump() is not called recursively when this model is
        nested inside another model.

        Has special handling for $defs (included as long as it is not empty)
        and $ref (always included).
        """
        # Get the serialized data from the handler
        data: dict[str, Any] = handler(self)

        # Rename value_type -> x-value-type for wire format before filtering.
        if "value_type" in data:
            data["x-value-type"] = data.pop("value_type")

        keys_to_keep: set[str] = {"$ref"}  # always keep $ref if present

        if hasattr(self, "__pydantic_fields_set__"):
            for key in self.__pydantic_fields_set__:
                # Translate the Python field name to the wire name.
                keys_to_keep.add("x-value-type" if key == "value_type" else key)

        # special handling for $defs, because aliasing breaks
        # __pydantic_fields_set__
        if "$defs" in data and not (
            isinstance(data["$defs"], Mapping) and len(data["$defs"]) == 0
        ):
            keys_to_keep.add("$defs")

        # Keep x-value-type if it has a value, regardless of __pydantic_fields_set__.
        if data.get("x-value-type") is not None:
            keys_to_keep.add("x-value-type")

        return {k: v for k, v in data.items() if k in keys_to_keep}

    def to_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> ValueType:
        """
        Resolves this schema to a Pydantic class.
        Always consult explicit registry identity first. The class's own published
        constraints and metadata do not change its identity. Additional constraints
        produce a subclass of that registered class, preserving its validators,
        serializers and casts; unknown extras are retained as schema metadata.

        References, if any, are resolved using self.defs first, then any
        extra_defs in order of decreasing precedence.
        """
        value_cls = ValueRegistry.DEFAULT.load_value(self)
        if value_cls is None:
            return self.build_value_cls(*extra_defs)
        published, intrinsic = _registered_constraints(value_cls)
        _, declared = _schema_constraints(self, *extra_defs)
        residual = {
            key: value
            for key, value in declared.items()
            if key not in intrinsic or intrinsic[key] != value
        }
        return _build_constrained_cls(
            value_cls, _constraint_field_map(published), residual
        )

    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> ValueType:
        """
        Builds a Pydantic class from this schema. References, if any, are
        resolved using self.defs first, then any extra_defs in order of decreasing precedence.

        Only reached for the catch-all ``Any`` shape (a bare
        ``BaseValueSchema``): every other member of the ``ValueSchema`` union
        overrides this method. That shape is also what a schema falls back to
        when it fails to match any of the more specific members, e.g. a bare
        ``items: {}``, ``additionalProperties: {}``, ``{}``, or a leaked
        ``oneOf``. Name the offending schema in the error, rather than raising
        a bare message that gives no clue which call produced it.
        """
        raise NotImplementedError(
            f"Cannot build a value class: schema matched no known "
            f"ValueSchema shape: {self!r}"
        )

    def to_field_info(
        self,
        *extra_defs: Mapping[str, ValueSchema],
        is_required: bool = False,
    ) -> FieldInfo:
        """
        Returns a Pydantic FieldInfo object for the schema.

        This method is somewhat lossy since it is almost impossible to
        faithfully convert the schema to a FieldInfo object.
        """
        annotation = self.to_value_cls(*extra_defs)
        if "default" not in self.model_fields_set:
            if not is_required:
                raise ValueError(
                    "Non-required properties need an explicit default; "
                    "the engine cannot represent an absent Value field"
                )
            return FieldInfo(
                annotation=annotation,
                title=self.title,
                description=self.description,
            )
        try:
            default_value = annotation.model_validate(self.default)
        except ValidationError as e:
            if is_required:
                # Required fields may optionally have a default value.
                # Invalid default values are ignored to be permissive.
                if self.default is not None:
                    e.add_note(f"Default value: {self.default}")
                    logger.warning(
                        f"Invalid default value for schema {self}", exc_info=True
                    )
                default_value = PydanticUndefined
            else:
                # Non-required fields must have a valid default value.
                # Failure to provide one is an unrecoverable error.
                e.add_note(f"Invalid default value for schema {self}")
                raise
        return FieldInfo(
            annotation=annotation,
            title=self.title,
            description=self.description,
            default=default_value,
        )


class BooleanValueSchema(BaseValueSchema):
    type: Final[Literal["boolean"]]

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[BooleanValue]:
        return BooleanValue


class NullValueSchema(BaseValueSchema):
    type: Final[Literal["null"]]

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[NullValue]:
        return NullValue


class IntegerValueSchema(BaseValueSchema):
    type: Final[Literal["integer"]]

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[IntegerValue]:
        return _build_constrained_cls(
            IntegerValue, _NUMERIC_FIELD_MAP, self.model_extra or {}
        )


class FloatValueSchema(BaseValueSchema):
    type: Final[Literal["number"]]

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[FloatValue]:
        return _build_constrained_cls(
            FloatValue, _NUMERIC_FIELD_MAP, self.model_extra or {}
        )


class StringValueSchema(BaseValueSchema):
    type: Final[Literal["string"]]
    enum: Sequence[str] | None = None
    pattern: str | None = None

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[StringValue]:
        # `pattern` is a declared field so it doesn't appear in model_extra;
        # merge it in explicitly so the constraint helper can see it.
        extras = dict(self.model_extra or {})
        if self.pattern is not None:
            extras["pattern"] = self.pattern
        if self.enum is not None:
            extras["enum"] = list(self.enum)
        return _build_constrained_cls(StringValue, _STRING_FIELD_MAP, extras)


class DateValueSchema(BaseValueSchema):
    type: Final[Literal["string"]]
    format: Final[Literal["date-time"]]

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[DateValue]:
        return DateValue


class ResultValueSchema(BaseValueSchema):
    """
    Matches the wire shape published by ``Result[T].to_value_schema()``: a
    tagged object with sibling ``ok`` / ``err`` members. ``ok`` and ``err``
    are the *type* schemas for each arm (``err`` is always ``ResultError``'s
    schema); the serialized *value* carries a ``tag`` plus exactly one
    populated payload. See docs/values.md for the full wire contract.
    """

    type: Final[Literal["object"]]
    ok: ValueSchema
    err: ValueSchema

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> ValueType:
        from .result import result_value_type

        item_type = self.ok.to_value_cls(self.defs, *extra_defs)
        return result_value_type(item_type)


class SequenceValueSchema(BaseValueSchema):
    type: Final[Literal["array"]]
    items: ValueSchema | Literal[True] = True

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[SequenceValue]:
        if self.items is True:
            T = Value
        else:
            T = self.items.to_value_cls(self.defs, *extra_defs)
        extras = dict(self.model_extra or {})
        if not extras:
            return SequenceValue[T]
        return _build_constrained_sequence_cls(T, extras)


class StringMapValueSchema(BaseValueSchema):
    type: Final[Literal["object"]]
    additionalProperties: ValueSchema | Literal[True] = True

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[StringMapValue]:
        if self.additionalProperties is True:
            item_type = Value
        else:
            item_type = self.additionalProperties.to_value_cls(self.defs, *extra_defs)
        extras = dict(self.model_extra or {})
        if not extras:
            return StringMapValue[item_type]
        return _build_constrained_map_cls(item_type, extras)


class DataValueSchema(BaseValueSchema):
    """
    Matches a DataValue[T] schema, for some class T that inherits from Data.
    """

    type: Final[Literal["object"]]

    # NOTE: recursive validation does not work unless this is a dict instead of a Mapping
    properties: dict[str, ValueSchema]
    additionalProperties: ValueSchema | bool = False
    required: Sequence[str] = Field(default_factory=list)

    def build_data_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[Data]:
        """
        Rebuilds the Data type T from the schema.
        This rebuilt Data type will not be the same as the original Data type T
        (i.e. equality checks will fail), but it will have the same fields.
        It will not necessarily have the same to_value_schema() as T, because
        the rebuilding process does not yet capture all of the descriptions from
        the original schema.
        """
        # TODO: capture the descriptions from the schema
        required_set = frozenset(self.required)
        defs = (self.defs, *extra_defs)
        properties = {
            k: (
                v.to_value_cls(*defs),
                v.to_field_info(*defs, is_required=k in required_set),
            )
            for k, v in self.properties.items()
        }
        return build_data_type(name=self.title or "Data", fields=properties)

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> type[DataValue]:
        D = self.build_data_cls(*extra_defs)
        return DataValue[D]


class UnionValueSchema(BaseValueSchema):
    anyOf: Sequence[ValueSchema]

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> ValueType:
        from .union import union_value_type

        members = tuple(
            schema.to_value_cls(self.defs, *extra_defs) for schema in self.anyOf
        )
        if not members:
            raise ValueError("UnionValueSchema requires at least one anyOf member")
        return union_value_type(*members)


class ReferenceValueSchema(BaseValueSchema):
    """
    A schema of the form
    { "$defs": { "foo": ... }, "$ref": "#/$defs/foo" }
    """

    model_config: ClassVar[ConfigDict] = ConfigDict(
        serialize_by_alias=True,  # already set in BaseValueSchema, but setting again here to be explicit
    )

    ref: str = Field(
        pattern=r"^#/\$defs/\w+$",
        serialization_alias="$ref",
        validation_alias="$ref",
    )

    @model_validator(mode="before")
    @classmethod
    def rename_ref_alias(cls, data: Any) -> Any:
        """
        A Pydantic bug causes model_validate() to break when called on an
        instance of ReferenceValueSchema.
        This is because the validator receives the .ref property from the
        object, whereas it is expecting $ref.
        To fix this, we move the property to the expected key.
        """
        if isinstance(data, Mapping) and ("$ref" not in data) and ("ref" in data):
            data = dict(data)
            data["$ref"] = data.pop("ref")
            return data
        return data

    @cached_property
    def id(self) -> str:
        _hash, _defs, id = self.ref.split("/")
        assert _hash == "#"
        assert _defs == "$defs"
        return id

    @override
    def build_value_cls(
        self,
        *extra_defs: Mapping[str, ValueSchema],
    ) -> ValueType:
        for defs in (self.defs, *extra_defs):
            if self.id in defs:
                target = defs[self.id]
                key = (id(target), self.id)
                stack = _REFERENCE_STACK.get()
                if key in stack:
                    raise ValueError(
                        f"Cyclic schema reference to definition {self.id!r}; "
                        "regenerate legacy schemas with explicit x-value-type identities"
                    )
                token = _REFERENCE_STACK.set((*stack, key))
                try:
                    return target.to_value_cls(self.defs, *extra_defs)
                finally:
                    _REFERENCE_STACK.reset(token)
        raise KeyError(f"Schema definition for {self.id} not found")


_REFERENCE_STACK: ContextVar[tuple[tuple[int, str], ...]] = ContextVar(
    "value_schema_reference_stack", default=()
)


def _schema_constraints(
    schema: BaseValueSchema, *extra_defs: Mapping[str, ValueSchema]
) -> tuple[BaseValueSchema, dict[str, Any]]:
    """Read root constraints, including those behind an enum/model wrapper ref."""
    shapes = [schema]
    scopes = (schema.defs, *extra_defs)
    seen = {id(schema)}
    while isinstance(schema, ReferenceValueSchema):
        target = next((defs[schema.id] for defs in scopes if schema.id in defs), None)
        if target is None or id(target) in seen:
            break
        seen.add(id(target))
        schema = target
        shapes.append(schema)
        scopes = (schema.defs, *scopes)
    constraints = {}
    for shape in reversed(shapes):
        wire = shape.model_dump(
            mode="json", include=set(shape.model_extra or {}) | {"pattern", "enum"}
        )
        constraints.update({key: wire[key] for key in shape.model_extra or {}})
        if isinstance(shape, StringValueSchema):
            for key in ("pattern", "enum"):
                if wire.get(key) is not None:
                    constraints[key] = wire[key]
    return schema, constraints


_REGISTERED_CONSTRAINTS: dict[ValueType, tuple[BaseValueSchema, dict[str, Any]]] = {}


def _registered_constraints(
    value_cls: ValueType,
) -> tuple[BaseValueSchema, dict[str, Any]]:
    # Value classes are immutable contracts. Schema generation never consults
    # the registry, so this does not freeze it during class-definition time.
    if value_cls not in _REGISTERED_CONSTRAINTS:
        _REGISTERED_CONSTRAINTS[value_cls] = _schema_constraints(
            value_cls.to_value_schema()
        )
    return _REGISTERED_CONSTRAINTS[value_cls]


def _constraint_field_map(schema: BaseValueSchema) -> dict[str, str]:
    if isinstance(schema, (IntegerValueSchema, FloatValueSchema)):
        return _NUMERIC_FIELD_MAP
    if isinstance(schema, StringValueSchema):
        return _STRING_FIELD_MAP
    if isinstance(schema, SequenceValueSchema):
        return _SEQUENCE_FIELD_MAP
    if isinstance(schema, StringMapValueSchema):
        return _MAP_FIELD_MAP
    return {}


type ValueSchema = (
    BooleanValueSchema
    | DataValueSchema
    | DateValueSchema
    | FloatValueSchema
    | IntegerValueSchema
    | NullValueSchema
    | ResultValueSchema
    | SequenceValueSchema
    | StringMapValueSchema
    | StringValueSchema
    | UnionValueSchema
    | ReferenceValueSchema  # must be handled second-to-last
    | BaseValueSchema  # must be handled last, corresponds to the Any catch-all
)


# yep, this is possible
class ValueSchemaValue(Value[ValueSchema]):
    pass


def validate_value_schema(schema: Any) -> ValueSchema:
    # idempotent: if the schema is already a ValueSchema, just return it
    if isinstance(schema, BaseValueSchema):
        return schema
    try:
        return ValueSchemaValue.model_validate(schema).root
    except ValidationError as e:
        raise ValueError(f"Invalid value schema: {schema}") from e


class FieldSchemaMappingValue(StringMapValue[ValueSchemaValue]):
    def to_data_schema(self, title: str) -> DataValueSchema:
        return DataValueSchema(
            type="object",
            title=title,
            properties={k: v.root for k, v in self.root.items()},
            additionalProperties=False,
            required=list(self.root.keys()),
        )

    @classmethod
    def from_fields(cls, **fields: ValueType) -> Self:
        return cls(
            {
                name: ValueSchemaValue(vtype.to_value_schema())
                for name, vtype in fields.items()
            }
        )


__all__ = [
    "BooleanValueSchema",
    "DataValueSchema",
    "DateValueSchema",
    "FieldSchemaMappingValue",
    "FloatValueSchema",
    "IntegerValueSchema",
    "NullValueSchema",
    "ReferenceValueSchema",
    "ResultValueSchema",
    "SequenceValueSchema",
    "StringMapValueSchema",
    "StringValueSchema",
    "UnionValueSchema",
    "ValueSchema",
    "ValueSchemaValue",
]
